#Solana RPC
SOLANA:
  #If the LP node has below this amount it will stop processing new swaps
  MIN_NATIVE_RESERVE: 0.1
  #Solana RPC URL to use, it is recommended to use a dedicated RPC endpoint from e.g. Helius (recommended), Quicknode, etc.
  RPC_URL: "https://api.mainnet-beta.solana.com"
  #Maximum fee in micro lamport/CU to use for transactions
  MAX_FEE_MICRO_LAMPORTS: 250000
  #File with the wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
  #Static tip (in lamports) to add to every transaction
  STATIC_TIP: 50000
  #Jito transaction relayer configuration
  #JITO:
  #  PUBKEY: "DttWaMuVvTiduZRnguLF7jNxTgiMBZ1hyAumKUiL2KRL"
  #  ENDPOINT: "https://frankfurt.mainnet.block-engine.jito.wtf/api/v1/transactions"

#Starknet RPC
STARKNET:
  #If the LP node has below this amount it will stop processing new swaps
  MIN_NATIVE_RESERVE: 100
  #Starknet RPC URL
  RPC_URL: "https://starknet.api.onfinality.io/public/rpc/v0_9"
  #Can also optionally specify an additional WS URL - allows for faster swap processing
  #WS_URL: ""
  #Gas price limits (higher bound)
  MAX_L1_FEE_GWEI: 20000000
  MAX_L2_FEE_GWEI: 4000000
  MAX_L1_DATA_FEE_GWEI: 10000000
  #Starknet chain
  CHAIN: "MAIN"

  #File with wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

  #Starknet quotes timeout
  AUTHORIZATION_TIMEOUT: 90

BOTANIX:
  #If the LP node has below this amount it will stop processing new swaps
  MIN_NATIVE_RESERVE: 0.0002
  #Botanix RPC URL, can either be an http or ws RPC
  RPC_URL: "wss://rpc.botanixlabs.com/ws"
  #Maximum block range that the underlying RPC provider supports
  MAX_LOGS_BLOCK_RANGE: 900
  #Fees
  MAX_FEE_GWEI: 2
  FEE_TIP_GWEI: 0.001
  #Botanix chain
  CHAIN: "MAINNET"

  #File with wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

  #Botanix quotes timeout
  AUTHORIZATION_TIMEOUT: 90

#Required APY option premium to be paid by the users as security deposit with BTC -> Solana swaps
SECURITY_DEPOSIT_APY: 80

#Bitcoin RPC
BITCOIND:
  PROTOCOL: "http"
  PORT: 8332
  HOST: "bitcoind"
  RPC_USERNAME: "user1"
  RPC_PASSWORD: "ThisIsAPassword"
  NETWORK: "mainnet"

#LND RPC
LND:
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
  MNEMONIC_BIRTHDAY_FILE: "/mnt/share/wallet/mnemonic-birthday.txt"
  WALLET_PASSWORD_FILE: "/mnt/share/wallet/password.txt"
  CERT_FILE: "/mnt/share/lnd/tls.cert"
  MACAROON_FILE: "/mnt/share/lnd/admin.macaroon"
  HOST: "lnd"
  PORT: 10009

#Lightning Network setup (chain -> BTC Lightning), uncomment these lines if you want to enable this swap direction
#TO_BTCLN:
#  #Total swap fee is calculated as BASE_FEE + {SWAP_VALUE}*FEE_PERCENTAGE
#  #Base fee (in BTC) to be paid by every swap
#  BASE_FEE: 0.00000010
#  #Fee (in %) to be charged on the swaps
#  FEE_PERCENTAGE: 0.3
#
#  #Minimum swappable amount in BTC (for lightning network swaps)
#  MIN: 0.00001000
#  #Maximum swappable amount in BTC (for lightning network swaps)
#  MAX: 0.01000000
#
#  #Allow lightning network swaps that cannot be probed first
#  ALLOW_NON_PROBABLE_SWAPS: true
#  #Allow lightning network swaps where the LN invoice has a very short expiry
#  ALLOW_LN_SHORT_EXPIRY: true
#
#  MAX_INFLIGHT_SWAPS: 100

#Lightning Network setup (BTC Lightning -> chain), uncomment these lines if you want to enable this swap direction
#FROM_BTCLN:
#  #Total swap fee is calculated as BASE_FEE + {SWAP_VALUE}*FEE_PERCENTAGE
#  #Base fee (in BTC) to be paid by every swap
#  BASE_FEE: 0.00000010
#  #Fee (in %) to be charged on the swaps
#  FEE_PERCENTAGE: 0.3
#
#  #Minimum swappable amount in BTC (for lightning network swaps)
#  MIN: 0.00001000
#  #Maximum swappable amount in BTC (for lightning network swaps)
#  MAX: 0.01000000
#
#  #Set expiration for lightning swaps invoices
#  INVOICE_EXPIRY_SECONDS: 90
#
#  #Maximum amounts for swap for gas
#  GAS_MAX:
#    STARKNET: 5
#    SOLANA: 0.03
#    BOTANIX: 0.00005
#
#  MAX_INFLIGHT_SWAPS: 100
#  MAX_INFLIGHT_AUTO_SWAPS: 20

#On-chain setup (chain -> BTC)
TO_BTC:
  #Total swap fee is calculated as BASE_FEE + {SWAP_VALUE}*FEE_PERCENTAGE
  #Base fee (in BTC) to be paid by every swap
  BASE_FEE: 0.00000150
  #Fee (in %) to be charged on the swaps
  FEE_PERCENTAGE: 0.3

  #Minimum swappable amount in BTC (for on-chain swaps)
  MIN: 0.00010000
  #Maximum swappable amount in BTC (for on-chain swaps)
  MAX: 0.05000000

  #Network fee buffer (in %), we charge the client this much more on the network
  # fee to accomodate for the possible fee rate increases in the near future 
  NETWORK_FEE_ADD_PERCENTAGE: 25

  MAX_INFLIGHT_SWAPS: 100

#On-chain setup (BTC -> chain)
FROM_BTC:
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
  #Use legacy swaps only for chains that do not support the newer SPV vault protocol
  LEGACY_SWAPS: "legacy_chains_only"

  #Total swap fee is calculated as BASE_FEE + {SWAP_VALUE}*FEE_PERCENTAGE
  #Base fee (in BTC) to be paid by every swap
  BASE_FEE: 0.00000150
  #Fee (in %) to be charged on the swaps
  FEE_PERCENTAGE: 0.3

  #Minimum swappable amount in BTC (for on-chain swaps)
  MIN: 0.00010000
  #Maximum swappable amount in BTC (for on-chain swaps)
  MAX: 0.05000000

  #Maximum "gas drop" for different chains
  GAS_MAX:
    STARKNET: 5
    SOLANA: 0.05
    BOTANIX: 0.00005

  MAX_INFLIGHT_SWAPS: 100

#Tradable assets setup
ASSETS:
  BBTC:
    chains:
      BOTANIX:
        address: "0x0000000000000000000000000000000000000000"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "$fixed-100000000"
  WBTC:
    chains:
      SOLANA:
        #Address of the token
        address: "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"
        #Decimal places
        decimals: 8
      STARKNET:
        address: "0x03fe2b97c1fd336e750087d68b9b867997fd64a2661ff3ca5a7c771641e8e7ac"
        decimals: 8
        spvVaultMultiplier: 1
    #Pricing source (using Binance), you can invert the pair by prepending "!"
    pricing: "WBTCBTC"
  USDC:
    chains:
      SOLANA:
        address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        decimals: 6
    pricing: "!BTCUSDC"
  USDT:
    chains:
      SOLANA:
        address: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"
        decimals: 6
    pricing: "!BTCUSDT"
  SOL:
    chains:
      SOLANA:
        address: "So11111111111111111111111111111111111111112"
        decimals: 9
        securityDepositAllowed: true
    pricing: "SOLBTC"
  ETH:
    chains:
      STARKNET:
        address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "ETHBTC"
  STRK:
    chains:
      STARKNET:
        address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
        decimals: 18
        securityDepositAllowed: true
        spvVaultMultiplier: 1000000000
    pricing: "STRKUSDT;!BTCUSDT"

#CLI - command line interface config
CLI:
  #CLI bind address
  ADDRESS: "0.0.0.0"
  #CLI TCP port
  PORT: 40221

#REST RFQ API config
REST:
  #REST API bind address
  ADDRESS: "0.0.0.0"
  #REST API port
  PORT: 443
  
#Automatic SSL certificate provisioning config
SSL_AUTO:
  #HTTP listen port to list for ACME challenges
  HTTP_LISTEN_PORT: 80
  #DNS proxy to use - mapping the server's IP address to a domain
  DNS_PROXY: "nodes.atomiq.exchange"

#Node extensions/plugins
PLUGINS:
  atomiq-archiver: "atomiq-archiver@latest"
